### ISSUE TITLE
Need logic for winning game

### ISSUE THREAD

**Issue by ThePhilgrim** [ThePhilgrim/minesweeper#17]
We need to implement logic so the program know when we've clicked every single square that is not in mine_locations.

**Comment by Akuli** [comment]
If you have a list of opened squares, this is quite easy: for each x in `range(width)` and y in `range(height)`, the pair `(x, y)` must be in the list of opened squares or in `mine_locations`, but not in both.

**Comment by Akuli** [comment]
The code is there, but needs some cleanup:
- [x] Improve variable names
- [x] Rename `01.gif` to something else
- [x] Update `image_sources.txt`
- [x] Delete `all_squares` list and use `self.width * self.height` instead of `len(all_squares)`
- [x] Use `self` instead of `current_game` when inside `class Game`
- [x] Hide the animation when new game starts
- [ ] Move `update()` function outside `open_squares()` method (make it another method?)
- [x] The label should go into `big_frame`, not `root`
- [x] Delete unnecessary `root.mainloop()`
